### ISSUE TITLE
[R1] Research into characteristics of GPU-related Problems on Judge Girl

### ISSUE THREAD

**Issue by Johnny850807** [Judge-Girl/Judge-K8S#1]
# Research into Characteristics of GPU-related Problems on Judge Girl

There are several GPU-related problems on Judge Girl, which vary in their characteristics. Some of them involve time limit, some of them are device-dependent (e.g. ask to print the number of GPUs on a node). The mentioned two kinds make the GPU scheduling more difficult.

Please perform the research and produce a document.

**Comment by Daniel1147** [comment]
[Problem 10098](https://judgegirl.csie.org/problem/0/10098) requires a program which prints device information of host. In this case, the results of submissions are coupled with the host running the judgement. Maybe we can offer a submission assignment policy for host-dependent problems so that this kind of problems can have their specific host to judge.
